set -e
true
true
/home/hannah/miniconda3/envs/genomics_env/bin/spades-core /home/hannah/LIFE748asm/GN6_spades/K21/configs/config.info /home/hannah/LIFE748asm/GN6_spades/K21/configs/isolate_mode.info
/home/hannah/miniconda3/envs/genomics_env/bin/spades-core /home/hannah/LIFE748asm/GN6_spades/K33/configs/config.info /home/hannah/LIFE748asm/GN6_spades/K33/configs/isolate_mode.info
/home/hannah/miniconda3/envs/genomics_env/bin/spades-core /home/hannah/LIFE748asm/GN6_spades/K55/configs/config.info /home/hannah/LIFE748asm/GN6_spades/K55/configs/isolate_mode.info
/home/hannah/miniconda3/envs/genomics_env/bin/spades-core /home/hannah/LIFE748asm/GN6_spades/K77/configs/config.info /home/hannah/LIFE748asm/GN6_spades/K77/configs/isolate_mode.info
/home/hannah/miniconda3/envs/genomics_env/bin/spades-core /home/hannah/LIFE748asm/GN6_spades/K99/configs/config.info /home/hannah/LIFE748asm/GN6_spades/K99/configs/isolate_mode.info
/home/hannah/miniconda3/envs/genomics_env/bin/spades-core /home/hannah/LIFE748asm/GN6_spades/K127/configs/config.info /home/hannah/LIFE748asm/GN6_spades/K127/configs/isolate_mode.info
/home/hannah/miniconda3/envs/genomics_env/bin/python3 /home/hannah/miniconda3/envs/genomics_env/share/spades/spades_pipeline/scripts/copy_files.py /home/hannah/LIFE748asm/GN6_spades/K127/before_rr.fasta /home/hannah/LIFE748asm/GN6_spades/before_rr.fasta /home/hannah/LIFE748asm/GN6_spades/K127/assembly_graph_after_simplification.gfa /home/hannah/LIFE748asm/GN6_spades/assembly_graph_after_simplification.gfa /home/hannah/LIFE748asm/GN6_spades/K127/final_contigs.fasta /home/hannah/LIFE748asm/GN6_spades/contigs.fasta /home/hannah/LIFE748asm/GN6_spades/K127/first_pe_contigs.fasta /home/hannah/LIFE748asm/GN6_spades/first_pe_contigs.fasta /home/hannah/LIFE748asm/GN6_spades/K127/strain_graph.gfa /home/hannah/LIFE748asm/GN6_spades/strain_graph.gfa /home/hannah/LIFE748asm/GN6_spades/K127/scaffolds.fasta /home/hannah/LIFE748asm/GN6_spades/scaffolds.fasta /home/hannah/LIFE748asm/GN6_spades/K127/scaffolds.paths /home/hannah/LIFE748asm/GN6_spades/scaffolds.paths /home/hannah/LIFE748asm/GN6_spades/K127/assembly_graph_with_scaffolds.gfa /home/hannah/LIFE748asm/GN6_spades/assembly_graph_with_scaffolds.gfa /home/hannah/LIFE748asm/GN6_spades/K127/assembly_graph.fastg /home/hannah/LIFE748asm/GN6_spades/assembly_graph.fastg /home/hannah/LIFE748asm/GN6_spades/K127/final_contigs.paths /home/hannah/LIFE748asm/GN6_spades/contigs.paths
true
/home/hannah/miniconda3/envs/genomics_env/bin/python3 /home/hannah/miniconda3/envs/genomics_env/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /home/hannah/LIFE748asm/GN6_spades/scaffolds.fasta --misc_dir /home/hannah/LIFE748asm/GN6_spades/misc --threshold_for_breaking_scaffolds 3
true
