---
title: "part1_graphs"
output: html_document
date: "2026-03-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

**Load required libraries**

```{r}
library(readr)
library(dplyr)
library(Biostrings)
library(tidyr)
library(ggplot2)
library(tidyverse)
```

**Retrieve results and combine into a new csv file**

```{r}
#create an empty list to store results
all_results <- list()

#run the following loop for both assembly types 
samples <- list('flye', 'SPAdes')
for (s in samples) {
  
  #create paths for bakta and prokka tsv files according to current assembly type
  p_path <- paste0("prokka_", s, ".tsv")
  b_path <- paste0("bakta_", s, ".tsv")
  f_path <- paste0("bakta_", s, ".fna") 
  
  #extract information from prokka
  p_data <- read.table(p_path, sep = "\t", header = TRUE, comment.char = "#", 
                       fill = TRUE, quote = "")
  #ensure consistent lowercase column names
  colnames(p_data) <- tolower(colnames(p_data))
  
  #store the total cds counts
  p_n_cds  <- sum(p_data$ftype == "CDS", na.rm = TRUE)
  #store number of trna and rrna
  p_n_trna <- sum(p_data$ftype == "tRNA", na.rm = TRUE)
  p_n_rrna <- sum(p_data$ftype == "rRNA", na.rm = TRUE)
  #count the number of functional products
  p_func   <- sum(!is.na(p_data$product) & !grepl("hypothetical", p_data$product))
  #calculate the functional percentage
  p_func_pct <- p_func / p_n_cds
  #calculate the number of hypothetical products
  p_hypo = p_n_cds - p_func
  
  #extract information from bakta
  b_data <- read.delim(b_path, sep = "\t", header = TRUE, comment.char = "#", 
                       quote = "", fill = TRUE, check.names = FALSE)
  #renmae columns to ensure smooth data extraction
  colnames(b_data) <- c(
    "sequence_id", "type", "start", "stop",
    "strand", "locus_tag", "gene", "product"
  )
  #store the total cds count
  b_n_cds  <- sum(b_data$type == "cds", na.rm = TRUE)
  #store number of trna and rrna
  b_n_trna <- sum(b_data$type == "tRNA", na.rm = TRUE)
  b_n_rrna <- sum(b_data$type == "rRNA", na.rm = TRUE)
  #create subset of cds only rows
  b_cds_only <- b_data[b_data$type == "cds", ]
  #count the number of functional products
  b_func <- sum(!is.na(b_cds_only$product) & 
                  !grepl("hypothetical", b_cds_only$product, ignore.case = TRUE))  
  #calculate the functional percentage
  b_func_pct <- b_func / b_n_cds
  #calculate the number of hypothetical products
  b_hypo  = b_n_cds - b_func
  
  #calculate GC content from prokka fna output
  fa <- readDNAStringSet(f_path)
  total_bp <- sum(width(fa))
  gc_fraction <- sum(letterFrequency(fa, c("G", "C"))) / total_bp
  
  #store all results in to the list
  all_results[[s]] <- tibble(
    sample        = s,
    genome_size   = total_bp,
    gc_content    = gc_fraction,
    prokka_CDS    = p_n_cds,
    bakta_CDS     = b_n_cds,
    prokka_tRNA   = p_n_trna,
    bakta_tRNA    = b_n_trna,
    prokka_rRNA   = p_n_rrna,
    bakta_rRNA    = b_n_rrna,
    prokka_func   = p_func,  
    prokka_hypo   = p_hypo,  
    bakta_func    = b_func,  
    bakta_hypo    = b_hypo,  
    prokka_func_pct = p_func_pct,
    bakta_func_pct  = b_func_pct
  ) 
}
#combine the results into a dataframe
summary_df <- bind_rows(all_results)
#save to a new csv file
write_csv(summary_df, "annotation_summary.csv")
```

**Plot 1: Gene, tRNA and rRNA counts**

```{r}
#prepare data for plotting by converting into a long format
p1_data <- summary_df %>% 
  select(sample, prokka_CDS, bakta_CDS, 
         prokka_tRNA, bakta_tRNA, prokka_rRNA, bakta_rRNA) %>%
  pivot_longer(-sample, names_to = "feature", values_to = "count") %>%
  #separate the sample name (eg prokka_flye) into two variables
  separate(feature, into = c("tool", "type"), sep = "_") %>% 
  #ensure sample and tool names are capitalised for neatness
  mutate(sample = recode(sample, "flye" = "Flye", "spades" = "SPAdes"), 
         tool = stringr::str_to_title(tool))

#create the plot
p1 <- ggplot(p1_data, aes(x = sample, y = count, fill = tool)) +
  #create bar columns, add position dodge to prevent overlaps
  geom_col(position = position_dodge(width = 0.9)) +
  #create text labels to show the count of each bar for clarity
  geom_text(aes(label = count),
            position = position_dodge(width = 0.9),
            vjust = -0.2, 
            size = 3.5,
            fontface = "bold") +
  #split the graph according to assembly type and create a stacked view with ncol
  facet_wrap(~type, scales = "free_y", ncol = 1) +
  #customise colors and theme
  scale_fill_manual(values = c("Prokka" = "#0072B2", "Bakta" = "#D55E00")) +
  theme_bw() +
  scale_y_continuous(expand = expansion(mult = c(0, 0.15))) +
  #set the correct labels
  labs(
    x = "Assembly Sample",
    y = "Feature Count",
    fill = "Annotation Tool",
    title = "Genomic Feature Comparison: Bakta vs. Prokka"
  )
p1
```

**Plot 2: Assembly size vs CDS count**

```{r}
#prepare data for plotting by converting to long format
p2_data <- summary_df %>%
  select(sample, genome_size, prokka_CDS, bakta_CDS) %>%
  pivot_longer(cols = c(prokka_CDS, bakta_CDS),
    names_to = "tool", values_to = "cds")%>%
  #rename labels for clear presentation
  mutate(tool = recode(tool,
                       "prokka_CDS" = "Prokka",
                       "bakta_CDS"  = "Bakta"))

#create the plot
p2 <- ggplot(p2_data, aes(x = genome_size / 1e6, y = cds, colour = tool)) +
  geom_point(size = 3, alpha = 0.8) +
  geom_smooth(method = "lm", se = TRUE) +
  scale_colour_manual(values = c("Prokka" = "#0072B2", "Bakta" = "#D55E00")) +
  theme_classic() +
  labs(
    title = "Assembly Size vs CDS Count",
    x = "Assembly Size (Mb)",
    y = "Number of CDS",
    colour = "Tool"
  )
p2
```

**Plot 3: Functional vs Hypothetical CDS**

```{r}
#prepare data for plotting
p3_data <- summary_df %>%
  select(sample, prokka_func, prokka_hypo, bakta_func, bakta_hypo) %>%
  pivot_longer(-sample, names_to = "feature", values_to = "count") %>%
  #separate the sample name (eg prokka_hypo) into two variables
  separate(feature, into = c("tool", "category"), sep = "_") %>% 
  mutate(
    category = recode(category, "func" = "Functional", "hypo" = "Hypothetical"),
    tool     = stringr::str_to_title(tool),
    sample   = stringr::str_to_title(sample)
  )

#create the plot
p3 <- ggplot(p3_data, aes(x = tool, y = count, fill = category)) +
  #create barchart columns
  geom_col(position = "fill", color = "white") +
  #separate panels for Flye and Spades
  facet_wrap(~sample) +
  scale_fill_manual(values = c("Functional" = "#0072B2", "Hypothetical" = "#D55E00")) +
  scale_y_continuous(labels = scales::percent) +
  theme_bw() + 
  labs(
    title = "Functional vs Hypothetical CDS", 
    x = "Tool",
    y = "Proportion",
    fill = "Category"
  )

p3
```

**GAI declaration**

Gemini 3 was used to assist the structuring of plot 1, details can be found in the GAI declaration part in the report.
